[phases.setup]
aptPkgs = ['default-mysql-client']

[phases.build]
cmds = [
  "bash -c 'cd backend && composer install --no-interaction --prefer-dist --optimize-autoloader'",
  "bash -c 'cd backend/frontend && npm install && npm run build'"
]

[start]
cmd = "bash -c 'cd backend && php artisan migrate --force && vendor/bin/heroku-php-apache2 public/'"

[nixpacks]
include = ["backend/**", "railway.json", "nixpacks.toml"]
exclude = ["admin-app/**"]