[phases.setup]
aptPkgs = ['default-mysql-client']

[phases.build]
cmds = [
  "cd backend && composer install --no-interaction --prefer-dist --optimize-autoloader",
  "cd backend/frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && php artisan migrate --force && vendor/bin/heroku-php-apache2 public/"

[nixpacks]
include = ["backend/**", "railway.json", "nixpacks.toml"]
exclude = ["admin-app/**"]